file:
  upload-dir: ./uploads

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  file-retention-days: 7

logging:
  level:
    org.springframework.web.client.RestTemplate: INFO